name: Build with Astro

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
